//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyVis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAccount()
        {
            this.tblTransactions = new HashSet<tblTransaction>();
        }
    
        public int account_id { get; set; }
        public string account_name { get; set; }
        public string account_abbrev { get; set; }
        public Nullable<decimal> opening_balance { get; set; }
        public Nullable<System.DateTime> opening_date { get; set; }
        public Nullable<int> account_type { get; set; }
        public Nullable<int> added_by { get; set; }
        public Nullable<System.DateTime> added_on { get; set; }
        public string account_number { get; set; }
        public string routing_number { get; set; }
        public Nullable<decimal> interest_rate { get; set; }
        public Nullable<int> active { get; set; }
        public string website { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> location_id { get; set; }
    
        public virtual tblLocation tblLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransaction> tblTransactions { get; set; }
    }
}
