//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyVis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int transaction_id { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public Nullable<decimal> transaction_amount { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<int> added_by { get; set; }
        public Nullable<System.DateTime> added_on { get; set; }
        public Nullable<int> event_id { get; set; }
        public string comments { get; set; }
        public Nullable<int> linked_transaction_id { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblLocation tblLocation { get; set; }
    }
}
